/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IncomeTaxWage;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author EMAN HASHIM
 */
public class IncomeTax extends javax.swing.JFrame {

    double Wages;
    double Salary;
    double Gross;
    double Tax;
    double Dedcuted;
    
    public IncomeTax() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelpayment = new javax.swing.JLabel();
        jComboBoxpayment = new javax.swing.JComboBox();
        jLabeltaxablewage = new javax.swing.JLabel();
        jLabel1untaxedincome = new javax.swing.JLabel();
        jTextFieldtaxablewage = new javax.swing.JTextField();
        jTextField1date = new javax.swing.JTextField();
        jTextFielddeduction = new javax.swing.JTextField();
        jTextField1untaxedincome = new javax.swing.JTextField();
        jTextFieldgrosspay = new javax.swing.JTextField();
        jTextFieldnet = new javax.swing.JTextField();
        jLabel1deduction = new javax.swing.JLabel();
        jLabelnet = new javax.swing.JLabel();
        jLabelgrosspay = new javax.swing.JLabel();
        jLabel1date = new javax.swing.JLabel();
        jButtoncalculate = new javax.swing.JButton();
        jButtonreset = new javax.swing.JButton();
        jButtonexit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlabelreferenceno = new javax.swing.JLabel();
        jLabeljobtitle = new javax.swing.JLabel();
        jLabelemployee = new javax.swing.JLabel();
        jTextFieldjobtitle = new javax.swing.JTextField();
        jTextFieldemployee = new javax.swing.JTextField();
        jTextFieldemployer = new javax.swing.JTextField();
        jTextFieldreferenceno = new javax.swing.JTextField();
        jLabelninumber = new javax.swing.JLabel();
        jLabelnicode = new javax.swing.JLabel();
        jLabelemployer = new javax.swing.JLabel();
        jLabeltaxperiod = new javax.swing.JLabel();
        jLabeltaxcode = new javax.swing.JLabel();
        jTextFieldninumber = new javax.swing.JTextField();
        jComboBoxtaxperiod = new javax.swing.JComboBox();
        jCombonicode = new javax.swing.JComboBox();
        jComboBoxtaxcode1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabelpayment.setText("Payment");

        jComboBoxpayment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1200", "1750", "1234", "6789", "6577" }));
        jComboBoxpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxpaymentActionPerformed(evt);
            }
        });

        jLabeltaxablewage.setText("Taxable Wage");

        jLabel1untaxedincome.setText("UnTaxedincome");

        jTextFieldtaxablewage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtaxablewageActionPerformed(evt);
            }
        });

        jTextFielddeduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddeductionActionPerformed(evt);
            }
        });

        jTextField1untaxedincome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1untaxedincomeActionPerformed(evt);
            }
        });

        jTextFieldnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnetActionPerformed(evt);
            }
        });

        jLabel1deduction.setText("Deduction");

        jLabelnet.setText("Net");

        jLabelgrosspay.setText("Gross Pay");

        jLabel1date.setText("Date");

        jButtoncalculate.setText("calculate");
        jButtoncalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncalculateActionPerformed(evt);
            }
        });

        jButtonreset.setText("reset");
        jButtonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresetActionPerformed(evt);
            }
        });

        jButtonexit.setText("exit");
        jButtonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtoncalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jButtonreset, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(jButtonexit, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldtaxablewage, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabelpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(56, 56, 56)
                            .addComponent(jComboBoxpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeltaxablewage, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1untaxedincome, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addComponent(jTextField1untaxedincome, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1date, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelgrosspay, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1deduction, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelnet, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldgrosspay, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1date, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnet, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFielddeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxpayment, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1date, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1date, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldgrosspay, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1untaxedincome, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1untaxedincome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelgrosspay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1deduction, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldtaxablewage, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFielddeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabeltaxablewage, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldnet, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelnet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtoncalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonreset, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonexit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 1390, 350));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1382, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 70));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlabelreferenceno.setText("Reference no");

        jLabeljobtitle.setText("JOb title");

        jLabelemployee.setText("employee");

        jTextFieldjobtitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldjobtitleActionPerformed(evt);
            }
        });

        jTextFieldreferenceno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldreferencenoActionPerformed(evt);
            }
        });

        jLabelninumber.setText("NI number");

        jLabelnicode.setText("NI code");

        jLabelemployer.setText("Employer");

        jLabeltaxperiod.setText("Tax Period");

        jLabeltaxcode.setText("Tax Code");

        jComboBoxtaxperiod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jCombonicode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ni1200", "ni1750", "ni1234", "ni6789", "TC657" }));

        jComboBoxtaxcode1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TC1200", "TC1750", "TC1234", "TC6789", "TC657" }));
        jComboBoxtaxcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxtaxcode1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabeljobtitle, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(jLabelemployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelemployer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabelreferenceno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldemployer, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldreferenceno, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldjobtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelnicode, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCombonicode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelninumber, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldninumber, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabeltaxperiod, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxtaxperiod, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabeltaxcode, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(286, 286, 286))))
                .addGap(75, 75, 75))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(1035, Short.MAX_VALUE)
                    .addComponent(jComboBoxtaxcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(79, 79, 79)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelreferenceno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldreferenceno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltaxperiod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxtaxperiod, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldemployer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelemployer, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabeltaxcode, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabelemployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldjobtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelnicode, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCombonicode, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabeljobtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelninumber, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldninumber, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jComboBoxtaxcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(186, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1390, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxpaymentActionPerformed
        if (jComboBoxpayment.getSelectedItem().equals("1200")){
        jTextField1untaxedincome.setText("1200");
        jTextFieldtaxablewage.setText("0");
        jTextFieldgrosspay.setText("1200");
        jTextFielddeduction.setText("0");
        jTextFielddeduction.setText("0");
        }
        
        else if (jComboBoxpayment.getSelectedItem().equals("1750")){
        
        jTextField1untaxedincome.setText("1200");
        Wages = Double.parseDouble( jTextField1untaxedincome.getText());
        Tax = 1750 - 1200;
        String WageTax = String.format("%.2f", Tax);
        jTextFieldtaxablewage.setText( WageTax);
        jTextFieldgrosspay.setText("1750");
        
        // for calculate
        Salary =(Tax * 20)/100;
        String Deduction = String.format("%.2f", Salary);
        jTextFielddeduction.setText(Deduction);
        
        }
        
        
        
        
        
         else if (jComboBoxpayment.getSelectedItem().equals("1234")){
        
        jTextField1untaxedincome.setText("1200");
        Wages = Double.parseDouble( jTextField1untaxedincome.getText());
        Tax = 1234 - 1200;
        String WageTax = String.format("%.2f", Tax);
        jTextFieldtaxablewage.setText( WageTax);
        jTextFieldgrosspay.setText("1234");
        // for calculate the deduction
        Salary =(Tax * 30)/100;
        String Deduction = String.format("%.2f", Salary);
        jTextFielddeduction.setText(Deduction);
        
        }
        
        
        
         else if (jComboBoxpayment.getSelectedItem().equals("6789")){
        
        jTextField1untaxedincome.setText("1200");
        Wages = Double.parseDouble( jTextField1untaxedincome.getText());
        Tax = 6789 - 1200;
        String WageTax = String.format("%.2f", Tax);
        jTextFieldtaxablewage.setText( WageTax);
        jTextFieldgrosspay.setText("6789");
        // for deductionn calculate
        
        Salary =(Tax * 27)/100;
        String Deduction = String.format("%.2f", Salary);
        jTextFielddeduction.setText(Deduction);
        
        }
        
        
         else if (jComboBoxpayment.getSelectedItem().equals("6577")){
        
        jTextField1untaxedincome.setText("1200");
        Wages = Double.parseDouble( jTextField1untaxedincome.getText());
        Tax = 6577 - 1200;
        String WageTax = String.format("%.2f", Tax);
        jTextFieldtaxablewage.setText( WageTax);
        jTextFieldgrosspay.setText("6577");
        
        // for deduction calculate
         Salary =(Tax * 40)/100;
        String Deduction = String.format("%.2f", Salary);
        jTextFielddeduction.setText(Deduction);
        
        }
        
        if (jComboBoxpayment.getSelectedItem().equals("0")){
        jTextField1untaxedincome.setText("0");
        jTextFieldtaxablewage.setText("0");
        jTextFieldgrosspay.setText("0");
        jTextFielddeduction.setText("0");
        }
    }//GEN-LAST:event_jComboBoxpaymentActionPerformed

    private void jButtoncalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncalculateActionPerformed
             
        
         double pay;
         Gross =  Double.parseDouble( jTextFieldgrosspay.getText());
         Dedcuted = Double.parseDouble( jTextFielddeduction.getText());
         pay = Gross - Dedcuted;
         
         // for netpay
         String netpay = String.format("%.2f", pay);
         
         jTextFieldnet.setText(netpay);
         
         // to set dollarsign in gross n wages
         
          String d = String.format("%.2f", Dedcuted);
          jTextFielddeduction.setText(d);
           String g = String.format("%.2f", Gross);
         jTextFieldgrosspay.setText(g);
    }//GEN-LAST:event_jButtoncalculateActionPerformed

    private void jTextFieldjobtitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldjobtitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldjobtitleActionPerformed

    private void jTextFieldreferencenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldreferencenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldreferencenoActionPerformed

    private void jTextField1untaxedincomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1untaxedincomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1untaxedincomeActionPerformed

    private void jTextFielddeductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddeductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddeductionActionPerformed

    private void jTextFieldnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnetActionPerformed

    private void jTextFieldtaxablewageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtaxablewageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtaxablewageActionPerformed
    private  JFrame frame;
    private void jButtonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexitActionPerformed
       
        frame = new JFrame();
        if(JOptionPane.showConfirmDialog(frame, "confirm if you want to exit", "Income Tax Calculator", 
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_jButtonexitActionPerformed

    private void jButtonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresetActionPerformed
        jTextFieldgrosspay.setText(null);
        jTextField1date.setText(null);
        jTextField1untaxedincome.setText(null);
        jTextFielddeduction.setText(null);
    jTextFieldemployee.setText(null);
    jTextFieldemployer.setText(null);
     jTextFieldgrosspay.setText(null);
     jTextFieldjobtitle.setText(null);
     jTextFieldnet.setText(null);
    jTextFieldninumber.setText(null);
  jTextFieldreferenceno.setText(null);
   jTextFieldtaxablewage.setText(null);
   
     jTextField1date.setText(null);
     
     // for combo box to reset we use setselet item 0 like below
      jComboBoxpayment.setSelectedIndex(0);
     jComboBoxtaxcode1.setSelectedIndex(0);
     jComboBoxtaxperiod.setSelectedIndex(0);
     jCombonicode.setSelectedIndex(0);
     
    }//GEN-LAST:event_jButtonresetActionPerformed

    private void jComboBoxtaxcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxtaxcode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxtaxcode1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncomeTax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncomeTax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncomeTax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncomeTax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncomeTax().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncalculate;
    private javax.swing.JButton jButtonexit;
    private javax.swing.JButton jButtonreset;
    private javax.swing.JComboBox jComboBoxpayment;
    private javax.swing.JComboBox jComboBoxtaxcode1;
    private javax.swing.JComboBox jComboBoxtaxperiod;
    private javax.swing.JComboBox jCombonicode;
    private javax.swing.JLabel jLabel1date;
    private javax.swing.JLabel jLabel1deduction;
    private javax.swing.JLabel jLabel1untaxedincome;
    private javax.swing.JLabel jLabelemployee;
    private javax.swing.JLabel jLabelemployer;
    private javax.swing.JLabel jLabelgrosspay;
    private javax.swing.JLabel jLabeljobtitle;
    private javax.swing.JLabel jLabelnet;
    private javax.swing.JLabel jLabelnicode;
    private javax.swing.JLabel jLabelninumber;
    private javax.swing.JLabel jLabelpayment;
    private javax.swing.JLabel jLabeltaxablewage;
    private javax.swing.JLabel jLabeltaxcode;
    private javax.swing.JLabel jLabeltaxperiod;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1date;
    private javax.swing.JTextField jTextField1untaxedincome;
    private javax.swing.JTextField jTextFielddeduction;
    private javax.swing.JTextField jTextFieldemployee;
    private javax.swing.JTextField jTextFieldemployer;
    private javax.swing.JTextField jTextFieldgrosspay;
    private javax.swing.JTextField jTextFieldjobtitle;
    private javax.swing.JTextField jTextFieldnet;
    private javax.swing.JTextField jTextFieldninumber;
    private javax.swing.JTextField jTextFieldreferenceno;
    private javax.swing.JTextField jTextFieldtaxablewage;
    private javax.swing.JLabel jlabelreferenceno;
    // End of variables declaration//GEN-END:variables
}
